### PR TITLE
Make multiple metrics on one line explicit.

### PR DESCRIPTION
**Pull request by danp**
The multi-metric support added as part of #27 considered anything matching `key=floatval` on the same line as `measure=foo` to be a metric in the form `foo.key` with a value of `floatval`.

This PR changes that a bit to make things more explicit: things matching `measure.key=floatval` on the same line as `measure=foo` will be considered to be a metric in the form `foo.key` with a value of `floatval`.

My motivation is cutting down on measurements sent to librato for metrics that won't be useful which translates primarily to lower cost.

### CODE REVIEW

**Comment by ryansmith3136** [comment]
@dpiddy One drawback to this approach is that it makes it nearly impossible to measure data from the Heroku router.

**Comment by danp** [comment]
@ryandotsmith I guess it depends on how far the special case #27 introduced for the router should go. For example, it act as if all keys from the router were prefixed with `measure.`.

**Comment by ryansmith3136** [comment]
@dpiddy I wish cost wasn't a motivating factor here. I really don't like `measure.*` in the log line. It seems like noise. Still racking my brains on this one...

**Comment by ryansmith3136** [comment]
@dpiddy thanks for the inspiration on this one. I pushed some bits around and brought over your ideas in #44.

**Pull request closed without merging**
