### PR TITLE
Don't convert float values to strings for Librato reporter

### LINKED ISSUE #63: Don't convert float values to strings for Librato reporter
Librato API can accept float values as flat floats and doesn't require the string conversion in the payload.

### PR DESCRIPTION
**Pull request by drio**
closes #63

### CODE REVIEW

**Comment by ryansmith3136** [comment]
@drio :+1: 

Go ahead and delete `ff()` and `fi()`. Also, I assume that you have tested this out locally? Are we 100% sure Librato's API will accept this data?

**Comment by mheffner** [comment]
Count should always be an integer, not float.

**Comment by drio** [comment]
@ryandotsmith 
Yes, I tested this locally. Yes, Librato's API will accept this data.

@mheffner 
The code generating the count values returns and integer. The struct that models metrics uses a float for the value field. When the metric count hits the API, value will be an integer.

**Comment by ryansmith3136** [comment]
We could certainly work around the count/int problem. However, I suspect that would require a bit of complexity or some sort of reflection. If Librato's API doesn't have a problem with receiving the data, then perhaps the current solution is good enough.

**Comment by mheffner** [comment]
Count will currently work with a decimal point (as a float). It'd still be good to fix that, but it could be done at a later time.

**Comment by ryansmith3136** [comment]
@mheffner It might be that Librato's support for complex measurements will help address this issue. Ideally, we don't have a `value` field in l2met's struct. Instead, we have a `sum`, `count`, `mean`, etc... field and each field's type will correspond to the ideal type required by Librato's API.

**Pull request merged**
