### PR TITLE
Support log runtime metrics

### PR DESCRIPTION
**Pull request by wolfeidau**
My first cut of support for heroku's log runtime metrics, which is related to #60

I have tested it with a bit of data I had in logs via log-shuttle and plan to deploy it soon.

Looking for feedback as I am very new to go and the project, I have done my best to provide test coverage and generally stick to the structure.

Cheers

### CODE REVIEW

**Comment by ryansmith3136** [comment]
@wolfeidau rad!

Interestingly enough, the measure=x val=y format used to be supported in l2met. It was removed as it wouldn't allow multiple metrics on a single line. However, there are still a few systems out there that use this legacy format.

Maybe it wouldn't be such a bad idea to support the legacy format. The only thing that I can see as being a problem is that your PR uses the syslog header's procid field for the source of the measurement. I wonder if there is a way that we can support both the legacy format and deal with the problems outlined in #60.

**Comment by wolfeidau** [comment]
Yeah no problem, I would also prefer to extract this from the message now that I have had a look at it closer.

I will pull the source attribute apart in the parser as suggested.

**Comment by wolfeidau** [comment]
Hopefully that is a bit better, I made sure there are tests which reflect the sample cases in #60.

**Comment by jamischarles** [comment]
+1

**Comment by jeremyvdw** [comment]
+1

**Comment by ryansmith3136** [comment]
I was able to chat with the Heroku guys who are responsible for emitting the runtime metrics. They are super interested in using the latest l2met log conventions. I think there is a really good chance they will be using the new logging format in the near term.

**Comment by ryansmith3136** [comment]
Also, it is really good to see people chime in for the demand here. So, spread the word. :)

**Comment by jamischarles** [comment]
@ryandotsmith I'm trying to build a reactive (immune) system for my heroku apps right now. Wondering if I could ping you for some questions on l2met and pulse vs riemann, clojure vs go etc...

Would greatly appreciate some insight. Let me know. Thx,
Jamis

**Comment by wolfeidau** [comment]
Man these guys didn't mess around.

Looks like it is already in production based on the changes to https://devcenter.heroku.com/articles/log-runtime-metrics 

I believe this pull request is now redundant.

**Comment by ryansmith3136** [comment]
Shout out to @nzoschke for making this happen.

**Comment by wolfeidau** [comment]
Was going to ask about the `sample#` format then remembered you CC'd me on #69 

Need to get some of this information into the readme so others understand these conventions.

I need to get an updated version into production which understands the new conventions, on the plus side I can for the most part drop the fork I am running.

On a side note would you be OK with me submitting a pull request to package this like https://github.com/heroku/log-shuttle/blob/master/Makefile which I believe you authored.. 

Would make deployment much easier for me.

**Comment by ryansmith3136** [comment]
Regarding the documentation of the logging conventions, take a look at the Usage article in the Wiki. I link to the wiki from the README.

**Comment by wolfeidau** [comment]
I always miss that, sorry mate.

It does indeed cover this thanks!

**Pull request closed without merging**
