### PR TITLE
Adding small bash script for signing drain urls after setup

### PR DESCRIPTION
**Pull request by BRMatt**

### CODE REVIEW

**Comment by ryansmith3136** [comment]
Rad! Where do you think we should document this feature? Maybe somewhere here: https://github.com/ryandotsmith/l2met/wiki ?

**Comment by BRMatt** [comment]
Personally I'd say in the README as that's where people usually look when they're getting started, though if you're trying to keep this stuff in the wiki(?) it looks like it'd fit in nicely under the signing example in "Usage".

**Comment by BRMatt** [comment]
btw the link to the README in the wiki homepage is 404ing

**Comment by BRMatt** [comment]
How about this:

> If you're running l2met on heroku you can use the `sign` script to generate a signed drain url:
> 
> ``` console
> $ ./sign my-librato-email@domain.com librato-api-key
> Drain URL: https://.....@l2met.herokuapp.com/logs
> ```

**Pull request merged**
